# -*- coding: utf-8 -*-
"""Indian_Painting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FC6No1mR8gsgxlduFQ220afAwWYmr75

**Install Libraries**
"""

import sys

# Install PyMuPDF for PDF processing
!{sys.executable} -m pip install PyMuPDF

# Install pytesseract for OCR
!{sys.executable} -m pip install pytesseract Pillow

# Install Tesseract OCR engine
!sudo apt update
!sudo apt install tesseract-ocr

print("Dependencies installed.")

"""#Extract text from the pdf"""

import fitz  # PyMuPDF
from PIL import Image
import pytesseract
import os

pdf_path = '/content/History_of_Indian_painting.pdf'
output_text_file = 'extracted_text.txt'

# Check if the PDF file exists
if not os.path.exists(pdf_path):
    print(f"Error: The PDF file '{pdf_path}' was not found.")
else:
    print(f"Processing PDF: {pdf_path}")
    text_data = []

    # Open the PDF
    with fitz.open(pdf_path) as doc:
        for page_num, page in enumerate(doc):
            print(f"Extracting text from page {page_num + 1}/{len(doc)}")
            # Render page to an image (high resolution for better OCR)
            pix = page.get_pixmap(matrix=fitz.Matrix(300 / 72, 300 / 72))

            # Convert to PIL Image
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

            # Perform OCR
            page_text = pytesseract.image_to_string(img)
            text_data.append(f"--- Page {page_num + 1} ---\n{page_text}")

    # Save extracted text to a file
    with open(output_text_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(text_data))

    print(f"OCR complete. Extracted text saved to '{output_text_file}'.")

    # Display the first few lines of the extracted text
    with open(output_text_file, 'r', encoding='utf-8') as f:
        first_lines = [next(f) for _ in range(20)] # Read first 20 lines
    print("\n--- First 20 lines of extracted text ---")
    print(''.join(first_lines))
    print("-----------------------------------------")

"""**Chunking and extracting metadata**"""

import sys
import os
import re # Import regex for page extraction

# Install langchain-text-splitters as RecursiveCharacterTextSplitter moved to this package
!{sys.executable} -m pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter # Corrected import path
from langchain_core.documents import Document # Corrected import for Document

# Path to the extracted text file
pdf_path = '/content/History_of_Indian_painting.pdf' # Define pdf_path for source metadata
output_text_file = 'extracted_text.txt'

# Function to extract page number from chunk content
def get_page_number_from_chunk(chunk_content):
    # Look for '--- Page X ---' pattern
    match = re.search(r'--- Page (\d+) ---', chunk_content)
    if match:
        return int(match.group(1))
    return None # Or return a default like 0 or -1 if no page marker found

# Check if the text file exists
if not os.path.exists(output_text_file):
    print(f"Error: The text file '{output_text_file}' was not found.")
else:
    print(f"Loading text from: {output_text_file}")
    with open(output_text_file, 'r', encoding='utf-8') as f:
        full_text = f.read()

    # Initialize the RecursiveCharacterTextSplitter
    # These parameters can be tuned based on the nature of the text and desired chunk size
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,  # Maximum number of characters in a chunk
        chunk_overlap=100,  # Overlap between chunks to maintain context
        length_function=len,  # Function to calculate chunk length
        add_start_index=True, # Add start index metadata initially, then custom add
    )

    # Split the text into chunks
    raw_texts = text_splitter.create_documents([full_text])

    # Now, add custom metadata to each chunk
    processed_texts = []
    for i, chunk in enumerate(raw_texts):
        # Create a new Document object or modify existing one
        new_metadata = chunk.metadata.copy()

        # Add chunk_id
        new_metadata["chunk_id"] = f"text_{i:04d}" # e.g., text_0000, text_0001

        # Add source
        new_metadata["source"] = os.path.basename(pdf_path) # Just the filename

        # Extract page number
        page_num = get_page_number_from_chunk(chunk.page_content)
        new_metadata["page"] = page_num if page_num is not None else "Unknown" # Handle cases where page marker might be missing

        # Add chunk_type
        new_metadata["chunk_type"] = "text"

        # Add placeholder for section
        # Automatic section detection is complex and requires specific document structure/parsing.
        # For now, we'll use a placeholder.
        new_metadata["section"] = "General" # Placeholder

        processed_texts.append(Document(page_content=chunk.page_content, metadata=new_metadata))

    texts = processed_texts # Update 'texts' to the processed list

    print(f"Created {len(texts)} chunks with custom metadata.")

    # Display the first few chunks with their new metadata
    print("\n--- First 3 chunks with custom metadata ---")
    for i, chunk in enumerate(texts[:3]):
        print(f"Chunk {i+1} (length: {len(chunk.page_content)}):")
        print(f"  Content snippet: {chunk.page_content[:200]}...") # Display first 200 chars
        print(f"  Metadata: {chunk.metadata}")
        print("----------------------")

import json
import os

# Define the output file name for the JSONL chunks
jsonl_output_file = 'chunks.jsonl'

# Ensure 'texts' list is available from the previous chunking step
if 'texts' not in locals() or not texts:
    print("Error: No text chunks found. Please run the text chunking cell first.")
else:
    print(f"Saving {len(texts)} chunks to '{jsonl_output_file}'...")
    with open(jsonl_output_file, 'w', encoding='utf-8') as f:
        for chunk in texts:
            # Convert Document object to a dictionary for JSON serialization
            chunk_dict = {
                "page_content": chunk.page_content,
                "metadata": chunk.metadata
            }
            f.write(json.dumps(chunk_dict, ensure_ascii=False) + '\n')
    print(f"Successfully saved chunks to '{jsonl_output_file}'.")

    # Display the first few lines of the JSONL file to verify
    print("\n--- First 5 lines of chunks.jsonl ---")
    with open(jsonl_output_file, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= 5: # Read first 5 lines
                break
            print(line.strip())
    print("------------------------------------")

"""#Extract images from the pdf"""

import sys
!{sys.executable} -m pip install opencv-python
print("OpenCV installed.")

import cv2
import numpy as np
import os
from PIL import Image
import fitz # PyMuPDF

pdf_path = '/content/History_of_Indian_painting.pdf'
input_images_full_pages_directory = 'extracted_images_full_pages' # New directory for full page images
output_illustrations_directory = 'refined_illustrations' # Directory for smaller illustrations

# 1. Create directories if they don't exist
if not os.path.exists(input_images_full_pages_directory):
    os.makedirs(input_images_full_pages_directory)
    print(f"Created directory: {input_images_full_pages_directory}")

if not os.path.exists(output_illustrations_directory):
    os.makedirs(output_illustrations_directory)
    print(f"Created directory: {output_illustrations_directory}")

# 2. Extract all pages from the PDF as images first
print(f"Extracting full pages from PDF: {pdf_path}...")
image_count_full_pages = 0
if os.path.exists(pdf_path):
    with fitz.open(pdf_path) as doc:
        for page_num, page in enumerate(doc):
            # Render page to a high-resolution image
            pix = page.get_pixmap(matrix=fitz.Matrix(300 / 72, 300 / 72))
            image_filename = os.path.join(input_images_full_pages_directory, f"page_{page_num + 1:04d}.png")
            pix.save(image_filename)
            image_count_full_pages += 1
    print(f"Extracted {image_count_full_pages} full pages to '{input_images_full_pages_directory}'.")
else:
    print(f"Error: PDF file not found at '{pdf_path}'. Cannot extract full pages.")


# 3. Process the extracted full-page images to find illustrations
illustration_count = 0
print(f"\nProcessing images from: {input_images_full_pages_directory} to refine illustrations...")

for filename in os.listdir(input_images_full_pages_directory):
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
        image_path = os.path.join(input_images_full_pages_directory, filename)

        # Load the image using OpenCV
        img = cv2.imread(image_path)
        if img is None:
            print(f"Could not load image: {image_path}")
            continue

        # Convert to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Apply Gaussian blur to reduce noise and help with contour detection
        blurred = cv2.GaussianBlur(gray, (5, 5), 0)

        # Use adaptive thresholding to get a binary image
        # This is often good for scanned documents with varying lighting
        thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                       cv2.THRESH_BINARY_INV, 11, 2)

        # Find contours
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # Iterate through contours and filter potential illustrations
        img_height, img_width = img.shape[:2]
        min_illustration_area = (img_width * img_height) * 0.005 # Min area 0.5% of page
        max_illustration_area = (img_width * img_height) * 0.80 # Max area 80% of page

        for i, contour in enumerate(contours):
            x, y, w, h = cv2.boundingRect(contour)
            area = cv2.contourArea(contour)
            aspect_ratio = w / float(h) if h > 0 else 0

            # Filter based on area, aspect ratio, and size relative to page
            # You may need to tune these parameters for best results
            if (area > min_illustration_area and area < max_illustration_area and
                w > 50 and h > 50 and # Minimum absolute dimensions
                aspect_ratio > 0.1 and aspect_ratio < 10): # Reasonable aspect ratio

                # Crop the illustration region
                illustration = img[y:y+h, x:x+w]

                # Save the cropped illustration
                output_filename = os.path.join(output_illustrations_directory, f"{os.path.splitext(filename)[0]}_illustration_{i}.jpg")
                cv2.imwrite(output_filename, illustration)
                illustration_count += 1

print(f"\nRefined image extraction complete. Total {illustration_count} potential illustrations extracted and saved to '{output_illustrations_directory}'.")

# List some of the extracted files to confirm
print("\n--- First 10 refined illustration files ---")
if os.path.exists(output_illustrations_directory):
    for i, filename in enumerate(os.listdir(output_illustrations_directory)):
        if i >= 10: break
        print(filename)
print("--------------------------------------")

"""**Image index file creation**"""

import os
import json
import re

output_illustrations_directory = 'refined_illustrations'
image_index_file = 'image_index.json'

image_index_data = []

if os.path.exists(output_illustrations_directory):
    print(f"Creating image index for files in '{output_illustrations_directory}'...")
    for filename in os.listdir(output_illustrations_directory):
        if filename.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.bmp')):
            # Extract page number from filename (e.g., page_0071_illustration_7148.jpg -> 71)
            match = re.search(r'page_(\d+)_illustration_(\d+)\.jpg', filename)
            page_num = "Unknown"
            if match:
                page_num = int(match.group(1)) # Convert to int

            # Generate a unique image_id (e.g., img_page_0071_ill_7148)
            image_id = f"img_{os.path.splitext(filename)[0].replace('page_', '').replace('_illustration_', '_ill_')}"

            image_index_data.append({
                "image_id": image_id,
                "filename": filename,
                "page": page_num
            })

    # Save the data to a JSON file
    with open(image_index_file, 'w', encoding='utf-8') as f:
        json.dump(image_index_data, f, ensure_ascii=False, indent=2)

    print(f"Image index successfully saved to '{image_index_file}'.")

    # Display the first few entries for verification
    print("\n--- First 5 entries of image_index.json ---")
    with open(image_index_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        for i, entry in enumerate(data[:5]):
            print(json.dumps(entry, indent=2))
            if i == 4: break
    print("-------------------------------------------")
else:
    print(f"Error: Directory '{output_illustrations_directory}' not found.")

"""#Image summarization using VLM"""

!pip install -U transformers

"""**VLM install**"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("image-text-to-text", model="llava-hf/llava-1.5-7b-hf")
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "url": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/p-blog/candy.JPG"},
            {"type": "text", "text": "What animal is on the candy?"}
        ]
    },
]
pipe(text=messages)

# Fix numpy version incompatibility
!pip install numpy==1.26.4 # Revert numpy to a version compatible with transformers and other libraries

import os
print("Numpy downgraded. Restarting runtime...")
os.kill(os.getpid(), 9) # Restart the Colab runtime

"""**Image summarization using VLM**"""

import os
import json
from PIL import Image # Used by transformers internally, but good to have for clarity
from transformers import pipeline, AutoProcessor, LlavaForConditionalGeneration, BitsAndBytesConfig
import torch # Import torch for dtype

# Install necessary libraries for 4-bit quantization
!pip install -qqq bitsandbytes accelerate

# Ensure pdf_path is defined for consistent source naming
pdf_path = '/content/History_of_Indian_painting.pdf'
pdf_source_filename = os.path.basename(pdf_path) if os.path.exists(pdf_path) else "Unknown_PDF_Source"

# Define file paths
image_index_file = 'image_index.json'
refined_illustrations_directory = 'refined_illustrations'
image_summaries_output_file = 'image_summaries.json'

# 1. Load image_index.json
if not os.path.exists(image_index_file):
    print(f"Error: {image_index_file} not found. Please ensure the image indexing cell was run successfully.")
else:
    with open(image_index_file, 'r', encoding='utf-8') as f:
        image_index_data = json.load(f)
    print(f"Loaded {len(image_index_data)} image entries from {image_index_file}.")

    # 2. Initialize the Image-to-Text Model with 4-bit quantization
    print("\nInitializing image-to-text model (llava-hf/llava-1.5-7b-hf with 4-bit quantization). This may take some time for download and setup...")
    try:
        # Define 4-bit quantization configuration
        nf4_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.float16 # Use float16 for computation
        )

        # Load the model with quantization config
        model = LlavaForConditionalGeneration.from_pretrained(
            "llava-hf/llava-1.5-7b-hf",
            quantization_config=nf4_config,
            device_map="auto" # Automatically maps the model to available devices
        )
        # Load the processor (tokenizer and image processor)
        processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")

        # Create the pipeline using the loaded model and processor
        image_to_text_pipe = pipeline(
            "image-text-to-text", # Changed task name to "image-text-to-text" as this is now the standard for multimodal models
            model=model,
            processor=processor # Pass the entire processor object
        )
        print("Image-to-text model loaded successfully with 4-bit quantization.")
    except Exception as e:
        print(f"Error loading image-to-text model: {e}")
        print("Please ensure you have run `!pip install -U transformers bitsandbytes accelerate` and have sufficient resources.")
        image_to_text_pipe = None # Indicate failure to load model

    if image_to_text_pipe:
        image_summaries = []
        print("\nGenerating summaries for extracted images...")

        for i, img_entry in enumerate(image_index_data):
            image_id = img_entry['image_id']
            filename = img_entry['filename'] # This is the filename from the image_index
            page_num = img_entry['page']
            full_image_path = os.path.join(refined_illustrations_directory, filename)

            if not os.path.exists(full_image_path):
                print(f"Warning: Image file not found at {full_image_path} for image_id {image_id}. Skipping.")
                continue

            print(f"Processing image {i+1}/{len(image_index_data)}: {filename} (page {page_num})")

            try:
                messages = [
                    {
                        "role": "user",
                        "content": [
                            {"type": "image", "path": full_image_path},
                            {"type": "text", "text": "You are an art history expert.\n\nDescribe this image with:\n- Art style and school\n- Historical period\n- Subject matter\n- Visual characteristics\n- Cultural significance.\n\nAvoid generic descriptions."}
                        ]
                    },
                ]

                # Generate summary from the model
                result = image_to_text_pipe(messages)

                summary_text = "No description generated."
                if result and isinstance(result, list) and len(result) > 0:
                    if 'generated_text' in result[0]:
                        generated_output = result[0]['generated_text']
                        # Check if generated_output is a string (expected common case)
                        if isinstance(generated_output, str):
                            summary_text = generated_output
                        # Check if generated_output is a list of messages (possible for conversational pipelines)
                        elif isinstance(generated_output, list):
                            # Find the last assistant message
                            for item in reversed(generated_output):
                                if isinstance(item, dict) and item.get('role') == 'assistant' and 'content' in item:
                                    summary_text = item['content']
                                    break
                        else:
                            print(f"WARNING: Unexpected type for 'generated_text': {type(generated_output)}")
                    else:
                        print("WARNING: 'generated_text' key not found in pipeline result.")
                else:
                    print("WARNING: Pipeline result is empty or not in expected list format.")

                # Clean up common LLaVA model prefixes from the generated text
                # Only apply if it's a string, which it should be after the extraction logic above.
                if isinstance(summary_text, str):
                    llava_prefix_custom = "A chat between a curious user and an AI assistant. USER: You are an art history expert.\n\nDescribe this image with:\n- Art style and school\n- Historical period\n- Subject matter\n- Visual characteristics\n- Cultural significance.\n\nAvoid generic descriptions. ASSISTANT:"
                    llava_prefix_long = "A chat between a curious user and an AI assistant. USER: Describe this image in detail. ASSISTANT:"
                    llava_prefix_short = "USER: Describe this image in detail. ASSISTANT:"

                    if summary_text.startswith(llava_prefix_custom):
                        summary_text = summary_text[len(llava_prefix_custom):].strip()
                    elif summary_text.startswith(llava_prefix_long):
                        summary_text = summary_text[len(llava_prefix_long):].strip()
                    elif summary_text.startswith(llava_prefix_short):
                        summary_text = summary_text[len(llava_prefix_short):].strip()
                else:
                    # This case should ideally not be reached with the improved extraction logic
                    print(f"CRITICAL WARNING: summary_text is not a string after extraction logic. Type: {type(summary_text)}")

                image_summaries.append({
                    "chunk_id": image_id,
                    "content": summary_text,
                    "metadata": {
                        "source": pdf_source_filename,
                        "filename": filename, # Add the filename here
                        "page": page_num,
                        "section": "Image Description", # Placeholder for now
                        "chunk_type": "image_summary"
                    }
                })

            except Exception as e:
                print(f"Error generating summary for image {filename}: {e}")
                image_summaries.append({
                    "chunk_id": image_id,
                    "content": f"Failed to generate summary due to an error: {str(e)}",
                    "metadata": {
                        "source": pdf_source_filename,
                        "filename": filename, # Add the filename even if summary fails
                        "page": page_num,
                        "section": "Image Description",
                        "chunk_type": "image_summary"
                    }
                })

        # 3. Save to image_summaries.json
        if image_summaries:
            with open(image_summaries_output_file, 'w', encoding='utf-8') as f:
                json.dump(image_summaries, f, ensure_ascii=False, indent=2)

            print(f"\nSuccessfully generated {len(image_summaries)} image summaries and saved to '{image_summaries_output_file}'.")

            # Display the first few entries for verification
            print("\n--- First 3 entries of image_summaries.json ---")
            with open(image_summaries_output_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for i, entry in enumerate(data[:3]):
                    print(json.dumps(entry, indent=2))
                    if i == 2: break
            print("----------------------------------------------")
        else:
            print(f"No image summaries were generated. '{image_summaries_output_file}' was not created.")

    else:
        print("Image summarization skipped because the model could not be loaded.")

"""**Combine text and image chunks to a single corpus**"""

import json
import os

# Define the input and output file names
text_chunks_file = 'chunks.jsonl'
image_summaries_file = 'image_summaries.json'
rag_corpus_output_file = 'rag_corpus.json'

rag_corpus = []

# 1. Load text chunks
if os.path.exists(text_chunks_file):
    print(f"Loading text chunks from '{text_chunks_file}'...")
    with open(text_chunks_file, 'r', encoding='utf-8') as f:
        for line in f:
            rag_corpus.append(json.loads(line))
    print(f"Loaded {len(rag_corpus)} text chunks.")
else:
    print(f"Warning: Text chunks file '{text_chunks_file}' not found. Skipping text chunk loading.")

# 2. Load image summaries
if os.path.exists(image_summaries_file):
    print(f"Loading image summaries from '{image_summaries_file}'...")
    with open(image_summaries_file, 'r', encoding='utf-8') as f:
        image_data = json.load(f)
        rag_corpus.extend(image_data)
    print(f"Loaded {len(image_data)} image summaries.")
else:
    print(f"Warning: Image summaries file '{image_summaries_file}' not found. Skipping image summary loading.")

# 3. Save the combined corpus to a new JSON file
if rag_corpus:
    with open(rag_corpus_output_file, 'w', encoding='utf-8') as f:
        json.dump(rag_corpus, f, ensure_ascii=False, indent=2)
    print(f"\nSuccessfully merged all content into '{rag_corpus_output_file}'. Total entries: {len(rag_corpus)}.")

    # Display the first few entries of the merged corpus for verification
    print("\n--- First 5 entries of rag_corpus.json ---")
    with open(rag_corpus_output_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        for i, entry in enumerate(data[:5]):
            print(json.dumps(entry, indent=2))
            if i == 4: break
    print("-------------------------------------------")
else:
    print("No content to merge. 'rag_corpus.json' was not created.")

"""#Generate Embedding - ChromaDB

**Install chromadb and sentence-transformers**

Correct version changes in libraries.
"""

import sys

# Uninstall potentially conflicting packages
!{sys.executable} -m pip uninstall -y chromadb opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc

# Reinstall chromadb and sentence-transformers, letting chromadb pull its compatible opentelemetry dependencies
!{sys.executable} -m pip install chromadb sentence-transformers

print("ChromaDB and Sentence-Transformers reinstalled.")

# Restart runtime to ensure new package versions are loaded
import os
print("Restarting runtime to apply package changes...")
os.kill(os.getpid(), 9)

"""**Vector database**

Combine text chunks and image summaries to a combined rag_corpus.json
"""

import json
import os
import chromadb
from chromadb.utils import embedding_functions

# Define paths
rag_corpus_file = 'rag_corpus.json'
chroma_db_path = './chroma_db'

# 1. Load the RAG Corpus
if not os.path.exists(rag_corpus_file):
    print(f"Error: RAG corpus file '{rag_corpus_file}' not found. Please ensure it was created.")
else:
    print(f"Loading RAG corpus from '{rag_corpus_file}'...")
    with open(rag_corpus_file, 'r', encoding='utf-8') as f:
        rag_corpus = json.load(f)
    print(f"Loaded {len(rag_corpus)} entries from the RAG corpus.")

    # 2. Initialize the Embedding Function
    # Using a common sentence-transformer model
    print("\nInitializing embedding function (all-MiniLM-L6-v2). This may download the model...")
    embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

    # 3. Initialize ChromaDB Client and Collection
    print(f"\nInitializing ChromaDB at '{chroma_db_path}'...")
    client = chromadb.PersistentClient(path=chroma_db_path)

    # Create or get a collection
    collection_name = "rag_document_collection"
    collection = client.get_or_create_collection(name=collection_name, embedding_function=embedding_function)
    print(f"ChromaDB collection '{collection_name}' ready.")

    # Prepare data for ChromaDB
    ids = []
    documents = []
    metadatas = []

    for entry in rag_corpus:
        # Correctly extract doc_id based on entry structure
        if 'chunk_id' in entry:
            doc_id = entry['chunk_id']
        elif 'metadata' in entry and 'chunk_id' in entry['metadata']:
            doc_id = entry['metadata']['chunk_id']
        else:
            # Fallback or error handling if chunk_id is not found
            print(f"Warning: 'chunk_id' not found in entry: {entry}")
            continue # Skip this entry or assign a default ID

        content = entry['page_content'] if 'page_content' in entry else entry['content'] # Handle both text and image summaries
        metadata = entry['metadata']

        ids.append(doc_id)
        documents.append(content)
        metadatas.append(metadata)

    # Added print for verification
    print("\n--- Sample metadata before adding to ChromaDB ---")
    for i, md in enumerate(metadatas):
        if 'chunk_type' in md and md['chunk_type'] == 'image_summary':
            print(f"Image summary metadata sample: {md}")
            break
    print("--------------------------------------------------")

    # 4. Add documents to ChromaDB (this will generate and store embeddings)
    print(f"\nAdding {len(documents)} documents to ChromaDB collection. This may take some time...")
    batch_size = 1000  # Adjust batch size based on memory and performance
    for i in range(0, len(documents), batch_size):
        batch_ids = ids[i:i + batch_size]
        batch_documents = documents[i:i + batch_size]
        batch_metadatas = metadatas[i:i + batch_size]
        collection.add(
            documents=batch_documents,
            metadatas=batch_metadatas,
            ids=batch_ids
        )
        print(f"  Processed {min(i + batch_size, len(documents))}/{len(documents)} documents.")

    print("\nEmbeddings generated and stored in ChromaDB successfully!")
    print(f"Total documents in collection: {collection.count()}")

    # Optional: Perform a small test query to verify
    print("\nPerforming a test query...")
    test_query = "What is Indian painting about?"
    results = collection.query(
        query_texts=[test_query],
        n_results=3,
        include=['documents', 'metadatas', 'distances']
    )
    print("Test Query Results:")
    for i, doc in enumerate(results['documents'][0]):
        print(f"  Result {i+1} (Distance: {results['distances'][0][i]:.2f}):")
        print(f"    Content: {doc[:200]}...") # Display first 200 chars
        print(f"    Metadata: {results['metadatas'][0][i]}")

# Install pyngrok and restart runtime for it to take effect
!pip install pyngrok -qq
import os
print("pyngrok installed. Restarting runtime...")
os.kill(os.getpid(), 9)

import sys

!{sys.executable} -m pip uninstall -y uvloop # Uninstall uvloop
!{sys.executable} -m pip install "uvicorn<0.20.0" fastapi

print("FastAPI and Uvicorn installed. Uvloop uninstalled.")
import os
print("Restarting runtime...")
os.kill(os.getpid(), 9)

# Explicitly update langchain and langchain-community and restart runtime to ensure module visibility
!pip install -U langchain langchain-community -qqq
import os
print("Langchain and Langchain-Community updated. Restarting runtime...")
os.kill(os.getpid(), 9)

!pip install openai

"""#RAG Backend"""

import uvicorn
import os
import chromadb
from chromadb.utils import embedding_functions
from google.colab import userdata # Import userdata to access secrets

from openai import OpenAI # Import OpenAI client
from typing import List, Dict, Any
import psutil # Import psutil to get process info
from datetime import datetime, timedelta # Import datetime and timedelta for uptime calculation

# --- RAG Pipeline Components Initialization ---

# ChromaDB path and collection name
chroma_db_path = './chroma_db'
collection_name = "rag_document_collection"

# Initialize the embedding function
# Use the same model as used during indexing
print("Initializing embedding function (all-MiniLM-L6-v2)...")
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

# Initialize ChromaDB Client and Collection
print(f"Initializing ChromaDB client and collection '{collection_name}' at '{chroma_db_path}'...")
client = chromadb.PersistentClient(path=chroma_db_path)

try:
    collection = client.get_or_create_collection(name=collection_name, embedding_function=embedding_function)
    print(f"ChromaDB collection '{collection_name}' loaded successfully. Total documents: {collection.count()}. Federate.")

    # --- DIAGNOSTIC: Verify metadata retrieval from the loaded collection ---
    if collection.count() > 0:
        print("\n--- Performing diagnostic query on loaded ChromaDB collection ---")
        # Fetch a few items directly to check metadata
        # Assuming 'image_summary' chunks have unique characteristics we can query for.
        # Or, retrieve the first few documents and check their metadata.
        sample_results = collection.query(
            query_texts=["description of an image"], # A generic query to find image summaries
            n_results=1,
            include=['metadatas']
        )
        if sample_results and sample_results['metadatas'] and len(sample_results['metadatas'][0]) > 0:
            first_sample_metadata = sample_results['metadatas'][0][0]
            print(f"Sample metadata from direct query: {first_sample_metadata}")
            if 'filename' in first_sample_metadata:
                print("  'filename' key IS present in metadata of direct query result.")
            else:
                print("  'filename' key IS NOT present in metadata of direct query result.")
        else:
            print("  No documents found or metadata missing in diagnostic query.")
        print("--- End of diagnostic query ---")

except Exception as e:
    print(f"Error loading ChromaDB collection: {e}")
    print("Please ensure the ChromaDB embedding generation step ran successfully.")
    collection = None # Indicate that the collection could not be loaded

# --- LLM Integration ---
# Retrieve OpenRouter API key from Colab secrets
OPENROUTER_API_KEY = userdata.get('qwen3.6') # Assuming 'qwen3.6' stores the OpenRouter key

openai_client = None # Renamed to avoid conflict with chromadb client
if not OPENROUTER_API_KEY:
    print("Warning: OPENROUTER_API_KEY not found in Colab secrets. LLM functionality will be disabled.")
else:
    print("Initializing OpenAI client for OpenRouter...")
    try:
        openai_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_API_KEY,
        )
        print("OpenAI client initialized successfully for OpenRouter.")
    except Exception as e:
        print(f"Error initializing OpenAI client: {e}. LLM functionality will be disabled.")

"""**Define and launch FastAPI**"""

import os
os.environ["ASGI_SERVER_NO_UVLOOP"] = "1" # Ensure uvicorn does not use uvloop

import asyncio # Import asyncio
# Explicitly set the default event loop policy to prevent uvloop from being used
asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())

import nest_asyncio
nest_asyncio.apply()

import uvicorn
import threading
import time
import psutil # Import psutil for process management


from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
# The following imports should already be available from the previous cell if it ran correctly.
# import chromadb
# from chromadb.utils import embedding_functions
# from google.colab import userdata
# from openai import OpenAI
# from typing import List, Dict, Any
# from datetime import datetime, timedelta

# Define the port for FastAPI
FASTAPI_PORT = 8000

# --- FastAPI Application Setup ---

app = FastAPI(
    title="RAG Document Query API",
    description="An API to query documents from a ChromaDB vector store and generate answers using an LLM."
)

# Record app start time for uptime calculation
app_start_time = datetime.now()

# Pydantic model for query requests
class QueryRequest(BaseModel):
    query: str
    n_results: int = 5 # Default to retrieving 5 results

# Pydantic model for ingest requests
class IngestDocument(BaseModel):
    content: str
    metadata: Dict[str, Any]
    id: str # Unique ID for the document

@app.get("/health")
async def health_check():
    llm_ready = openai_client is not None
    indexed_documents = 0
    if collection:
        try:
            indexed_documents = collection.count()
        except Exception as e:
            print(f"Error getting document count from ChromaDB: {e}")

    # Calculate uptime
    current_time = datetime.now()
    uptime_duration = current_time - app_start_time
    uptime_str = str(uptime_duration).split('.')[0] # Remove microseconds for cleaner output

    return {
        "status": "ok",
        "message": "RAG API is running",
        "llm_ready": llm_ready,
        "indexed_documents": indexed_documents,
        "uptime": uptime_str
    }

@app.post("/ingest")
async def ingest_document(doc: IngestDocument):
    if collection is None:
        raise HTTPException(status_code=503, detail="ChromaDB collection not initialized.")
    try:
        collection.add(
            documents=[doc.content],
            metadatas=[doc.metadata],
            ids=[doc.id]
        )
        return {"status": "success", "message": f"Document with ID {doc.id} ingested.", "id": doc.id}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error during document ingestion: {str(e)}")

@app.post("/query")
async def query_documents(request: QueryRequest):
    if collection is None:
        raise HTTPException(status_code=503, detail="ChromaDB collection not initialized.")

    print(f"Received query: '{request.query}' with n_results: {request.n_results}")
    try:
        # Step 1: Retrieve relevant documents from ChromaDB
        results = collection.query(
            query_texts=[request.query],
            n_results=request.n_results,
            include=['documents', 'metadatas', 'distances']
        )

        retrieved_docs_content = []
        formatted_results = []
        if results and results['documents'] and results['documents'][0]:
            for i in range(len(results['documents'][0])):
                doc_content = results['documents'][0][i]
                doc_metadata = results['metadatas'][0][i]
                doc_distance = results['distances'][0][i]

                retrieved_docs_content.append(doc_content)
                formatted_results.append({
                    "content": doc_content,
                    "metadata": doc_metadata,
                    "distance": doc_distance
                })

        # Step 2: Generate an answer using the LLM if available
        if openai_client:
            if retrieved_docs_content:
                context_str = "\n\n".join(retrieved_docs_content)
            else:
                context_str = "No relevant documents found in the knowledge base."

            messages = [
                {"role": "system", "content": f"You are an AI assistant for a document. Use the following context to answer the question. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nContext: {context_str}"},
                {"role": "user", "content": f"Question: {request.query}"}
            ]

            response = openai_client.chat.completions.create(
                extra_headers={
                    "HTTP-Referer": "https://colab.research.google.com/", # Required for OpenRouter rankings
                    "X-Title": "Google Colab Notebook", # Optional
                },
                model="qwen/qwen3.6-plus:free", # Updated to 'qwen/qwen3.6-plus:free'
                messages=messages,
                max_tokens=512,
                temperature=0.1
            )
            llm_response = response.choices[0].message.content
            return {"query": request.query, "answer": llm_response, "sources": formatted_results}
        else:
            # If LLM is not initialized, return only retrieval results
            return {"query": request.query, "answer": "LLM not initialized. Showing raw retrieval results.", "sources": formatted_results}

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error during query processing: {str(e)}")

# Function to gracefully stop previous uvicorn instances on the port
def stop_fastapi_server(port):
    print(f"Checking for existing processes on port {port}...")
    for proc in psutil.process_iter(['pid', 'name', 'connections']):
        try:
            for conn in proc.connections(kind='inet'):
                if conn.laddr.port == port:
                    print(f"Found process {proc.name()} (PID: {proc.pid}) using port {port}. Terminating...")
                    proc.terminate()
                    proc.wait(timeout=3) # Wait for termination
                    if proc.is_running():
                        proc.kill() # Force kill if still running
                        print(f"Process {proc.pid} force killed.")
                    else:
                        print(f"Process {proc.pid} terminated successfully.")
        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            pass
    print("Cleanup complete.")

# Function to run FastAPI app
def run_fastapi():
    # Explicitly create a new event loop for this thread
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    uvicorn.run(app, host="0.0.0.0", port=FASTAPI_PORT)

# --- Main execution block ---
# Stop any lingering FastAPI server before starting a new one
stop_fastapi_server(FASTAPI_PORT)

# Start FastAPI in a separate thread
print(f"Starting FastAPI app on port {FASTAPI_PORT}...")
api_thread = threading.Thread(target=run_fastapi)
api_thread.daemon = True # Allow the main program to exit without waiting for this thread
api_thread.start()

# Give some time for the server to spin up
time.sleep(5)

print(f"FastAPI app is running locally at http://127.0.0.1:{FASTAPI_PORT}")
print("You can now interact with your API using a tool like `requests`:")
print("requests.post(\"http://127.0.0.1:8000/query\", json={'query': 'Your question here'})")

"""**Query - Text based**"""

import requests

url = "http://127.0.0.1:8000/query"

payload = {
    "query": "Explain Mughal miniature painting",
    "n_results": 5 # Include n_results as it's a required field in the QueryRequest Pydantic model
}

r = requests.post(url, json=payload)
print(r.status_code)
print(r.json())

"""**Query - Image based**"""

import requests
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

url = "http://127.0.0.1:8000/query"

payload = {
    "query": "Show an image of a Buddha statue from the book",
    "n_results": 5
}

try:
    r = requests.post(url, json=payload)
    r.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    response_data = r.json()
    print(r.status_code)
    print(response_data)

    # Check if there are image sources and try to display the first one
    if 'sources' in response_data:
        image_sources = [s for s in response_data['sources'] if s['metadata'].get('chunk_type') == 'image_summary']
        if image_sources:
            print("\n--- Displaying First Relevant Image Source ---")
            first_image_source = image_sources[0]
            filename = first_image_source['metadata'].get('filename')
            page_num = first_image_source['metadata'].get('page', 'Unknown')

            if filename:
                image_path = os.path.join('refined_illustrations', filename)
                if os.path.exists(image_path):
                    print(f"Found image file: {image_path} (from page {page_num})")
                    try:
                        img = mpimg.imread(image_path)
                        plt.imshow(img)
                        plt.title(f"Image from Page {page_num} ({filename})")
                        plt.axis('off') # Hide axes ticks and labels
                        plt.show()
                    except Exception as img_e:
                        print(f"Error displaying image {image_path}: {img_e}")
                else:
                    print(f"Image file not found at expected path: {image_path}")
            else:
                print("No filename found in metadata for the image source.")
        else:
            print("No image summaries found in the retrieved sources.")

except requests.exceptions.RequestException as e:
    print(f"Error making request to FastAPI: {e}")
    if hasattr(e, 'response') and e.response is not None:
        print(f"Response Status Code: {e.response.status_code}")
        print(f"Response Body: {e.response.json()}")

"""**Query - Table based**"""

import requests

url = "http://127.0.0.1:8000/query"

payload = {
    "query": "What Indian pigments are mentioned in the appendix section? List them out.",
    "n_results": 5 # Retrieve enough results to cover the appendix content
}

try:
    r = requests.post(url, json=payload)
    r.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    response_data = r.json()
    print("Status Code:", r.status_code)
    print("Query Answer:", response_data['answer'])
    print("\n--- Sources ---")
    for source in response_data['sources']:
        print(f"Content snippet: {source['content'][:150]}...")
        print(f"Metadata: {source['metadata']}")
        print("------------------")

except requests.exceptions.RequestException as e:
    print(f"Error making request to FastAPI: {e}")
    if hasattr(e, 'response') and e.response is not None:
        print(f"Response Status Code: {e.response.status_code}")
        print(f"Response Body: {e.response.json()}")

"""**/Ingsetion check**"""

import requests
import json

url = "http://127.0.0.1:8000/ingest"

ingest_payload = {
  "id": "custom_doc_001",
  "content": "Indian miniature painting flourished under Mughal patronage...",
  "metadata": {
    "source": "Manual Ingest",
    "page": 120,
    "section": "Mughal Painting",
    "chunk_type": "text"
  }
}

print("--- Ingesting Custom Document ---")
print(f"ID: {ingest_payload['id']}")
print(f"Content snippet: {ingest_payload['content'][:150]}...")
print(f"Metadata: {ingest_payload['metadata']}")

# Make the POST request
try:
    r = requests.post(url, json=ingest_payload)
    r.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    print("\n--- Ingestion Response ---")
    print(f"Status Code: {r.status_code}")
    print(f"Response: {r.json()}")
except requests.exceptions.RequestException as e:
    print(f"\nError making request to FastAPI: {e}")
    if hasattr(e, 'response') and e.response is not None:
        print(f"Response Status Code: {e.response.status_code}")
        print(f"Response Body: {e.response.json()}")

"""**/Health check**"""

import requests

url = "http://127.0.0.1:8000/health"

try:
    response = requests.get(url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    print("FastAPI /health endpoint status:")
    print(response.json())
except requests.exceptions.RequestException as e:
    print(f"Error connecting to FastAPI health endpoint: {e}")
    print("Please ensure the FastAPI server is running in a separate thread.")